/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analyses_get"];
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Delete Analysis */
        delete: operations["delete_analysis_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Analysis
         * @description The full report as Markdown (download).
         */
        get: operations["export_analysis_analyses__analysis_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_analyses__analysis_id__interview_get"];
        put?: never;
        /**
         * Prepare Interview
         * @description "Prepare Me for Interview". Idempotent: returns the stored set if there is one.
         */
        post: operations["prepare_interview_analyses__analysis_id__interview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Analysis
         * @description Same resume and documents, new job description. Extraction of the profile is
         *     served from the LLM cache, so only the job side costs anything.
         */
        post: operations["rerun_analysis_analyses__analysis_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a resume/supporting file, or paste supporting text. Text is extracted now.
         */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_health_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisCreate */
        AnalysisCreate: {
            /** Extra Text */
            extra_text?: string | null;
            /** Jd Text */
            jd_text: string;
            /**
             * Resume Doc Id
             * Format: uuid
             */
            resume_doc_id: string;
            /** Supporting Doc Ids */
            supporting_doc_ids?: string[];
        };
        /** AnalysisCreated */
        AnalysisCreated: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "parsing" | "extracting" | "scoring" | "advising" | "done" | "failed";
        };
        /** AnalysisRerun */
        AnalysisRerun: {
            /** Jd Text */
            jd_text: string;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Fit Score */
            fit_score: number | null;
            /** Gaps */
            gaps: components["schemas"]["Gap"][] | null;
            /** Id */
            id: string;
            job_requirements: components["schemas"]["JobRequirements"] | null;
            learning_path: components["schemas"]["LearningPath"] | null;
            llm_usage: components["schemas"]["LLMUsage"];
            /** Matches */
            matches: components["schemas"]["RequirementMatch"][] | null;
            /** Potential Score */
            potential_score: number | null;
            /** Prompt Versions */
            prompt_versions: {
                [key: string]: unknown;
            };
            /** Rejected Suggestions */
            rejected_suggestions: components["schemas"]["RejectedSuggestion"][] | null;
            /** Scoring Version */
            scoring_version: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "parsing" | "extracting" | "scoring" | "advising" | "done" | "failed";
            student_profile: components["schemas"]["StudentProfile"] | null;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fit Score */
            fit_score: number | null;
            /** Id */
            id: string;
            /** Potential Score */
            potential_score: number | null;
            /** Role Title */
            role_title: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "parsing" | "extracting" | "scoring" | "advising" | "done" | "failed";
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "supporting";
            /** Text */
            text?: string | null;
        };
        /** Certification */
        Certification: {
            /**
             * Date
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            date: string | null;
            /**
             * Evidence
             * @description Short verbatim quote (under 200 characters) copied exactly from that document.
             */
            evidence: string;
            /** Issuer */
            issuer: string | null;
            /** Name */
            name: string;
            /**
             * Source
             * @description Id of the document this came from, exactly as given, e.g. "RESUME" or "S1".
             */
            source: string;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Char Count */
            char_count: number;
            /** Filename */
            filename: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "supporting" | "jd" | "extra_text";
            /** Sections */
            sections: string[];
        };
        /** Education */
        Education: {
            /** Degree */
            degree: string | null;
            /**
             * End
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            end: string | null;
            /**
             * Evidence
             * @description Short verbatim quote (under 200 characters) copied exactly from that document.
             */
            evidence: string;
            /** Field Of Study */
            field_of_study: string | null;
            /**
             * Grade
             * @description GPA/CGPA/percentage as written, if stated.
             */
            grade: string | null;
            /** Institution */
            institution: string;
            /**
             * Source
             * @description Id of the document this came from, exactly as given, e.g. "RESUME" or "S1".
             */
            source: string;
            /**
             * Start
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            start: string | null;
        };
        /**
         * EvidenceRef
         * @description One piece of the student's evidence for a requirement.
         */
        EvidenceRef: {
            /** Context */
            context: string;
            /** Direct */
            direct: boolean;
            /** Index */
            index: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "project" | "experience" | "education" | "certification";
            /** Label */
            label: string;
            /** Snippet */
            snippet: string;
            /** Source */
            source: string;
        };
        /** Experience */
        Experience: {
            /**
             * Employment Type
             * @enum {string}
             */
            employment_type: "full_time" | "part_time" | "internship" | "freelance" | "research" | "volunteer" | "other";
            /**
             * End
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            end: string | null;
            /**
             * Evidence
             * @description Short verbatim quote (under 200 characters) copied exactly from that document.
             */
            evidence: string;
            /**
             * Highlights
             * @description Responsibilities and achievements as stated.
             */
            highlights: string[];
            /** Organization */
            organization: string;
            /**
             * Source
             * @description Id of the document this came from, exactly as given, e.g. "RESUME" or "S1".
             */
            source: string;
            /**
             * Start
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            start: string | null;
            /** Technologies */
            technologies: string[];
            /** Title */
            title: string;
        };
        /** Gap */
        Gap: {
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "domain" | "experience" | "education" | "soft_skill";
            /**
             * Importance
             * @enum {string}
             */
            importance: "must" | "nice";
            /** Name */
            name: string;
            /** Requirement Index */
            requirement_index: number;
            /** Skill Id */
            skill_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** InterviewQuestion */
        InterviewQuestion: {
            /**
             * Category
             * @enum {string}
             */
            category: "technical" | "general" | "personal" | "project";
            /** Dimension */
            dimension?: string | null;
            source: components["schemas"]["QuestionSource"];
            /** Text */
            text: string;
            /** Topic */
            topic?: string | null;
        };
        /** InterviewSet */
        InterviewSet: {
            /** General */
            general: components["schemas"]["InterviewQuestion"][];
            /** Personal */
            personal: components["schemas"]["InterviewQuestion"][];
            /** Projects */
            projects: components["schemas"]["ProjectQuestions"][];
            /** Technical */
            technical: components["schemas"]["InterviewQuestion"][];
        };
        /** JobRequirements */
        JobRequirements: {
            /** Company */
            company: string | null;
            /** Requirements */
            requirements: components["schemas"]["Requirement"][];
            /** Role Title */
            role_title: string | null;
            /** Seniority */
            seniority: ("intern" | "entry" | "mid" | "senior" | "lead") | null;
        };
        /** LLMUsage */
        LLMUsage: {
            /** Cached Calls */
            cached_calls: number;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** LearningPath */
        LearningPath: {
            /** Steps */
            steps: components["schemas"]["LearningStep"][];
            /** Total Hours */
            total_hours: number;
        };
        /** LearningResource */
        LearningResource: {
            /** Est Hours */
            est_hours: number | null;
            /** Free */
            free: boolean;
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Skill Id */
            skill_id: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "docs" | "course" | "video" | "book" | "practice";
            /** Url */
            url: string;
        };
        /** LearningStep */
        LearningStep: {
            /** Est Hours */
            est_hours: number | null;
            /** For Requirements */
            for_requirements: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "gap" | "prerequisite";
            /** Name */
            name: string;
            /** Resources */
            resources: components["schemas"]["LearningResource"][];
            /** Skill Id */
            skill_id: string | null;
            /** Step */
            step: number;
            /** Unlocks */
            unlocks: string[];
            /** Why */
            why: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string | null;
            /** User Id */
            user_id: string;
        };
        /** Project */
        Project: {
            /**
             * Challenges
             * @description Problems faced or solved, if stated.
             */
            challenges: string[];
            /**
             * End
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            end: string | null;
            /**
             * Evidence
             * @description Short verbatim quote (under 200 characters) copied exactly from that document.
             */
            evidence: string;
            /**
             * Highlights
             * @description Concrete technical details: what was built, how, design decisions.
             */
            highlights: string[];
            /**
             * Metrics
             * @description Quantified results as stated (numbers, scale).
             */
            metrics: string[];
            /** Name */
            name: string;
            /**
             * Role
             * @description The student's role, if stated.
             */
            role: string | null;
            /**
             * Source
             * @description Id of the document this came from, exactly as given, e.g. "RESUME" or "S1".
             */
            source: string;
            /**
             * Start
             * @description "YYYY-MM", "YYYY", "present", or null if not stated.
             */
            start: string | null;
            /**
             * Summary
             * @description One or two sentences on what the project is.
             */
            summary: string;
            /** Technologies */
            technologies: string[];
            /** Url */
            url: string | null;
        };
        /** ProjectQuestions */
        ProjectQuestions: {
            /** Project */
            project: string;
            /** Questions */
            questions: components["schemas"]["InterviewQuestion"][];
            /** Technologies */
            technologies: string[];
        };
        /** QuestionSource */
        QuestionSource: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "github" | "template";
            /** Label */
            label: string;
            /** License */
            license: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Url */
            url: string | null;
        };
        /** RejectedSuggestion */
        RejectedSuggestion: {
            /** Reason */
            reason: string;
            /** Suggested Text */
            suggested_text: string;
        };
        /** Requirement */
        Requirement: {
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "domain" | "experience" | "education" | "soft_skill";
            /**
             * Evidence
             * @description Short verbatim quote from the job description.
             */
            evidence: string;
            /**
             * Importance
             * @description must = required/essential; nice = preferred/bonus/plus.
             * @enum {string}
             */
            importance: "must" | "nice";
            /**
             * Min Years
             * @description Minimum years if stated, else null.
             */
            min_years: number | null;
            /**
             * Name
             * @description One atomic requirement, e.g. 'Python', 'REST APIs', '2+ years backend experience', 'B.Tech in Computer Science'.
             */
            name: string;
        };
        /**
         * RequirementMatch
         * @description Scorer + GapClassifier output for one requirement.
         */
        RequirementMatch: {
            /** Best Strength */
            best_strength: number;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "strong_in_resume" | "weak_in_resume" | "missing_from_resume_but_evidenced" | "true_gap";
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "domain" | "experience" | "education" | "soft_skill";
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Importance
             * @enum {string}
             */
            importance: "must" | "nice";
            /**
             * Method
             * @enum {string}
             */
            method: "taxonomy" | "implied" | "fuzzy" | "llm" | "none";
            /** Min Years */
            min_years: number | null;
            /** Name */
            name: string;
            /** Requirement Index */
            requirement_index: number;
            /** Resume Strength */
            resume_strength: number;
            /** Resume Years */
            resume_years: number | null;
            /** Skill Id */
            skill_id: string | null;
            /** Total Years */
            total_years: number | null;
            /** Weight */
            weight: number;
        };
        /** SkillMention */
        SkillMention: {
            /**
             * Context
             * @description Where in the document the skill appears.
             * @enum {string}
             */
            context: "skills_section" | "project" | "experience" | "education" | "certification" | "summary" | "other";
            /**
             * Context Name
             * @description Project or job name when context is project or experience, else null.
             */
            context_name: string | null;
            /**
             * Evidence
             * @description Short verbatim quote (under 200 characters) copied exactly from that document.
             */
            evidence: string;
            /**
             * Name
             * @description Skill, tool, language or concept, as written.
             */
            name: string;
            /**
             * Source
             * @description Id of the document this came from, exactly as given, e.g. "RESUME" or "S1".
             */
            source: string;
        };
        /** StudentProfile */
        StudentProfile: {
            /** Certifications */
            certifications: components["schemas"]["Certification"][];
            /** Education */
            education: components["schemas"]["Education"][];
            /** Experience */
            experience: components["schemas"]["Experience"][];
            /**
             * Headline
             * @description The student's own summary line, if any.
             */
            headline: string | null;
            /** Projects */
            projects: components["schemas"]["Project"][];
            /**
             * Skills
             * @description One entry per place a skill appears; the same skill may repeat.
             */
            skills: components["schemas"]["SkillMention"][];
        };
        /** Suggestion */
        Suggestion: {
            /**
             * Action
             * @enum {string}
             */
            action: "add_skill" | "add_project" | "expand_project" | "add_experience" | "expand_experience" | "add_certification" | "add_education_detail";
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Id */
            id: string;
            /** Quote */
            quote: string;
            /** Quote Source */
            quote_source: string;
            /** Quote Source Label */
            quote_source_label: string;
            /** Rationale */
            rationale: string;
            /** Requirement Indexes */
            requirement_indexes: number[];
            /** Requirement Names */
            requirement_names: string[];
            /**
             * Section
             * @enum {string}
             */
            section: "skills" | "projects" | "experience" | "education" | "certifications" | "summary";
            /** Suggested Text */
            suggested_text: string;
            /** Target */
            target: string | null;
            /** Uplift */
            uplift: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analyses_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
        };
    };
    create_analysis_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_analysis_analyses__analysis_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_analyses__analysis_id__interview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_interview_analyses__analysis_id__interview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_analysis_analyses__analysis_id__rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRerun"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_health_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
}
